### ISSUE TITLE
Recon Squad dont have a Sniper

### ISSUE THREAD

**Issue by jokoho48** [TaktiCool/ArmaAtWar#533] opened 2017-03-18 20:13 UTC

**Comment by Hoegnison** [comment] 2017-03-29 19:15
couldnt reproduce, which mission? Was the error that the sniper kit did not have a sniper rifle or that the rec on squad didnt have a sniper kit.

**Comment by jokoho48** [comment] 2017-03-29 19:18
i think @netfusion repored that originaly. and i think he forgot that the sniper is a Limited Kit

**Comment by Hoegnison** [comment] 2017-06-10 12:19
We couldnt reproduce. I will close this for now.

**Closed by Hoegnison** 2017-06-10 12:19 UTC
Labels: task
